#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
// #define SPECULATIVE_HOLD

// Speculative hold: neutralize flashing mods on tap rollback
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_RIGHT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI) }

#define COMBO_TERM 25

// getreuer: Unfortunately, some applications drop or misorder fast key events.
// This is a partial fix to slow down the rate at which macros are sent.
#define TAP_CODE_DELAY 5

// Holding Shift while Caps Word is active inverts the shift state.
#define CAPS_WORD_INVERT_ON_SHIFT
// When idle, turn off Caps Word after 5 seconds.
#define CAPS_WORD_IDLE_TIMEOUT 5000

// Don't apply custom shift keys with mods other than Shift.
#define CUSTOM_SHIFT_KEYS_NEGMODS ~MOD_MASK_SHIFT

// Only apply custom shift keys on layer 0
#define CUSTOM_SHIFT_KEYS_LAYER_MASK (1 << 0)

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 10

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 200

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 50

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 16

#define SERIAL_NUMBER "amZp5/Wv7bYl"  // used by zsa/oryx module
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1
#define HSS(report) host_system_send(record->event.pressed ? report : 0); return false
#define HCS(report) host_consumer_send(record->event.pressed ? report : 0); return false

// Cyclotab: https://getreuer.info/posts/keyboards/cyclotab/index.html
#define CYCLOTAB_KEYS LGUI(KC_TAB)

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 200
#define QUICK_TAP_TERM_PER_KEY
#define FLOW_TAP_TERM 100
#define RGB_MATRIX_STARTUP_SPD 60

// Lumino: https://getreuer.info/posts/keyboards/lumino/index.html
// Cycles brightness 0-40-100%
#define LUMINO_BOOT_COLOR RGB_WHITE

// PaletteFx: https://getreuer.info/posts/keyboards/palettefx/index.html
// RM_NEXT / RM_PREV 	Cycle through effects.
// RM_HUEU / RM_HUED 	Cycle through palettes.
// RM_SATU / RM_SATD 	Increase / decrease saturation (color vibrancy).
// RM_VALU / RM_VALD 	Increase / decrease value (brightness).
// RM_SPDU / RM_SPDD 	Increase / decrease animation speed.

// PaletteFx effects
#define PALETTEFX_GRADIENT_ENABLE
#define PALETTEFX_FLOW_ENABLE
#define PALETTEFX_RIPPLE_ENABLE
#define PALETTEFX_SPARKLE_ENABLE
#define PALETTEFX_VORTEX_ENABLE
#define PALETTEFX_REACTIVE_ENABLE
#define RGB_MATRIX_KEYREACTIVE_ENABLED  // needed for PALETTEFX_REACTIVE

// PaletteFx palettes
#define PALETTEFX_AFTERBURN_ENABLE
#define PALETTEFX_AMBER_ENABLE
#define PALETTEFX_BADWOLF_ENABLE
#define PALETTEFX_CARNIVAL_ENABLE
#define PALETTEFX_CLASSIC_ENABLE
#define PALETTEFX_DRACULA_ENABLE
#define PALETTEFX_GROOVY_ENABLE
#define PALETTEFX_NOTPINK_ENABLE
#define PALETTEFX_PHOSPHOR_ENABLE
#define PALETTEFX_POLARIZED_ENABLE
#define PALETTEFX_ROSEGOLD_ENABLE
#define PALETTEFX_SPORT_ENABLE
#define PALETTEFX_SYNTHWAVE_ENABLE
#define PALETTEFX_THERMAL_ENABLE
#define PALETTEFX_VIRIDIS_ENABLE
#define PALETTEFX_WATERMELON_ENABLE

#ifdef RGB_MATRIX_ENABLE
// Disable most built-in RGB Matrix effects in favor of PaletteFx.
#  undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#  undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#  undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  undef ENABLE_RGB_MATRIX_BREATHING
#  undef ENABLE_RGB_MATRIX_BAND_SAT
#  undef ENABLE_RGB_MATRIX_BAND_VAL
#  undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#  undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#  undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#  undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  undef ENABLE_RGB_MATRIX_CYCLE_ALL
#  undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  undef ENABLE_RGB_MATRIX_DUAL_BEACON
#  undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#  undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#  undef ENABLE_RGB_MATRIX_RAINDROPS
#  undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  undef ENABLE_RGB_MATRIX_HUE_BREATHING
#  undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#  undef ENABLE_RGB_MATRIX_HUE_WAVE
#  undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#  undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#  undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#  undef ENABLE_RGB_MATRIX_STARLIGHT
#  undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#  undef ENABLE_RGB_MATRIX_RIVERFLOW

#  undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#  undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  undef ENABLE_RGB_MATRIX_SPLASH
#  undef ENABLE_RGB_MATRIX_MULTISPLASH
#  undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#  undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif  // RGB_MATRIX_ENABLE
